"""Initial schema

Revision ID: bce914369109
Revises: 
Create Date: 2026-07-13 10:35:32.608380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce914369109'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuracy_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=True),
    sa.Column('metric', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accuracy_snapshots_id'), 'accuracy_snapshots', ['id'], unique=False)
    op.create_table('debounce_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debounce_entries_key'), 'debounce_entries', ['key'], unique=False)
    op.create_index(op.f('ix_debounce_entries_scope'), 'debounce_entries', ['scope'], unique=False)
    op.create_table('fusion_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('elo_diff_range', sa.String(length=20), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('metric', sa.String(length=20), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('learned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fusion_weights_id'), 'fusion_weights', ['id'], unique=False)
    op.create_table('jingcai_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.String(length=20), nullable=False),
    sa.Column('issue_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sale_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draw_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draw_result', sa.JSON(), nullable=True),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jingcai_issues_id'), 'jingcai_issues', ['id'], unique=False)
    op.create_index(op.f('ix_jingcai_issues_issue_id'), 'jingcai_issues', ['issue_id'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('feature_dim', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('flag', sa.String(length=10), nullable=True),
    sa.Column('fifa_rank', sa.Integer(), nullable=True),
    sa.Column('elo', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=10), nullable=True),
    sa.Column('continent', sa.String(length=50), nullable=True),
    sa.Column('squad_size', sa.Integer(), nullable=True),
    sa.Column('form_last5', sa.String(length=10), nullable=True),
    sa.Column('form_factor', sa.Float(), nullable=True),
    sa.Column('avg_goals_scored', sa.Float(), nullable=True),
    sa.Column('avg_goals_conceded', sa.Float(), nullable=True),
    sa.Column('avg_xg', sa.Float(), nullable=True),
    sa.Column('avg_xga', sa.Float(), nullable=True),
    sa.Column('possession', sa.Float(), nullable=True),
    sa.Column('pass_completion', sa.Float(), nullable=True),
    sa.Column('shots_per_game', sa.Float(), nullable=True),
    sa.Column('stats_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recent_results', sa.String(length=20), nullable=True),
    sa.Column('recent_goals_scored', sa.Float(), nullable=True),
    sa.Column('recent_goals_conceded', sa.Float(), nullable=True),
    sa.Column('home_away_factor', sa.Float(), nullable=True),
    sa.Column('weather_adaptability', sa.Float(), nullable=True),
    sa.Column('tactical_style', sa.String(length=20), nullable=True),
    sa.Column('coach_rating', sa.Float(), nullable=True),
    sa.Column('rest_days', sa.Integer(), nullable=True),
    sa.Column('key_injuries', sa.String(length=200), nullable=True),
    sa.Column('squad_fatigue_index', sa.Float(), nullable=True),
    sa.Column('key_players_available', sa.Integer(), nullable=True),
    sa.Column('key_players_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_sessions_id'), 'ai_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_code', sa.String(length=50), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_name', sa.String(length=10), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('match_type', sa.Enum('WORLD_CUP', 'FRIENDLY', 'WARM_UP', 'QUALIFIER', name='matchtype'), nullable=True),
    sa.Column('competition', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'UPCOMING', 'LIVE', 'FINISHED', 'POSTPONED', name='matchstatus'), nullable=True),
    sa.Column('venue_type', sa.String(length=20), nullable=True),
    sa.Column('weather', sa.String(length=20), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pitch_condition', sa.String(length=20), nullable=True),
    sa.Column('schedule_density', sa.String(length=20), nullable=True),
    sa.Column('odds_home', sa.Float(), nullable=True),
    sa.Column('odds_draw', sa.Float(), nullable=True),
    sa.Column('odds_away', sa.Float(), nullable=True),
    sa.Column('odds_source', sa.String(length=100), nullable=True),
    sa.Column('opening_odds_home', sa.Float(), nullable=True),
    sa.Column('opening_odds_draw', sa.Float(), nullable=True),
    sa.Column('opening_odds_away', sa.Float(), nullable=True),
    sa.Column('opening_odds_source', sa.String(length=100), nullable=True),
    sa.Column('opening_odds_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_odds_home', sa.Float(), nullable=True),
    sa.Column('closing_odds_draw', sa.Float(), nullable=True),
    sa.Column('closing_odds_away', sa.Float(), nullable=True),
    sa.Column('closing_odds_source', sa.String(length=100), nullable=True),
    sa.Column('odds_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('odds_degraded', sa.Boolean(), nullable=True),
    sa.Column('actual_home_goals', sa.Integer(), nullable=True),
    sa.Column('actual_away_goals', sa.Integer(), nullable=True),
    sa.Column('actual_outcome', sa.String(length=10), nullable=True),
    sa.Column('ht_home_goals', sa.Integer(), nullable=True),
    sa.Column('ht_away_goals', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('is_broadcasted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_code')
    )
    op.create_index(op.f('ix_matches_group_name'), 'matches', ['group_name'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_kickoff_at'), 'matches', ['kickoff_at'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('league', sa.String(length=50), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('key_passes', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_stats_team_id'), 'player_stats', ['team_id'], unique=False)
    op.create_table('user_quant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_bankroll', sa.Float(), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=50), nullable=True),
    sa.Column('preferred_leagues', sa.JSON(), nullable=True),
    sa.Column('ai_behavior_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quant_profiles_id'), 'user_quant_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_quant_profiles_user_id'), 'user_quant_profiles', ['user_id'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('default_play_type', sa.String(length=20), nullable=True),
    sa.Column('show_ev', sa.Boolean(), nullable=True),
    sa.Column('show_probability', sa.Boolean(), nullable=True),
    sa.Column('notify_odds_change', sa.Boolean(), nullable=True),
    sa.Column('notify_match_start', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_id'), 'ai_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ai_messages_session_id'), 'ai_messages', ['session_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('parsed_value', sa.JSON(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingest_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processor', sa.String(length=50), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('betting_exchange_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('home_ratio', sa.Float(), nullable=True),
    sa.Column('draw_ratio', sa.Float(), nullable=True),
    sa.Column('away_ratio', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_betting_exchange_volumes_match_id'), 'betting_exchange_volumes', ['match_id'], unique=True)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_table('jingcai_issue_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('handicap', sa.Integer(), nullable=True),
    sa.Column('rq_odds', sa.Text(), nullable=True),
    sa.Column('score_odds', sa.Text(), nullable=True),
    sa.Column('goals_odds', sa.Text(), nullable=True),
    sa.Column('half_odds', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['jingcai_issues.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jingcai_issue_matches_id'), 'jingcai_issue_matches', ['id'], unique=False)
    op.create_index(op.f('ix_jingcai_issue_matches_issue_id'), 'jingcai_issue_matches', ['issue_id'], unique=False)
    op.create_index(op.f('ix_jingcai_issue_matches_match_id'), 'jingcai_issue_matches', ['match_id'], unique=False)
    op.create_table('license_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('license_type', sa.Enum('MATCH', 'TOURNAMENT', name='licensetype'), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('tournament', sa.String(length=50), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_keys_id'), 'license_keys', ['id'], unique=False)
    op.create_index(op.f('ix_license_keys_key'), 'license_keys', ['key'], unique=True)
    op.create_table('live_odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('odds_home', sa.Float(), nullable=False),
    sa.Column('odds_draw', sa.Float(), nullable=False),
    sa.Column('odds_away', sa.Float(), nullable=False),
    sa.Column('match_minute', sa.Integer(), nullable=True),
    sa.Column('live_score_home', sa.Integer(), nullable=True),
    sa.Column('live_score_away', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_odds_snapshots_id'), 'live_odds_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_live_odds_snapshots_match_id'), 'live_odds_snapshots', ['match_id'], unique=False)
    op.create_index(op.f('ix_live_odds_snapshots_recorded_at'), 'live_odds_snapshots', ['recorded_at'], unique=False)
    op.create_table('match_ai_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_checksum', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_ai_reports_match_id'), 'match_ai_reports', ['match_id'], unique=True)
    op.create_table('match_bookmaker_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=30), nullable=False),
    sa.Column('odds_home', sa.Float(), nullable=False),
    sa.Column('odds_draw', sa.Float(), nullable=False),
    sa.Column('odds_away', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_bookmaker_odds_id'), 'match_bookmaker_odds', ['id'], unique=False)
    op.create_index(op.f('ix_match_bookmaker_odds_match_id'), 'match_bookmaker_odds', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_bookmaker_odds_recorded_at'), 'match_bookmaker_odds', ['recorded_at'], unique=False)
    op.create_table('odds_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('odds_home', sa.Float(), nullable=False),
    sa.Column('odds_draw', sa.Float(), nullable=False),
    sa.Column('odds_away', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=True),
    sa.Column('is_real', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_history_id'), 'odds_history', ['id'], unique=False)
    op.create_index(op.f('ix_odds_history_match_id'), 'odds_history', ['match_id'], unique=False)
    op.create_index(op.f('ix_odds_history_recorded_at'), 'odds_history', ['recorded_at'], unique=False)
    op.create_table('prediction_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_snapshots_id'), 'prediction_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_snapshots_match_id'), 'prediction_snapshots', ['match_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('play_type', sa.Enum('SPF', 'RQ', 'SCORE', 'GOALS', 'HALF', name='playtype'), nullable=False),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('input_checksum', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_match_id'), 'predictions', ['match_id'], unique=False)
    op.create_index(op.f('ix_predictions_play_type'), 'predictions', ['play_type'], unique=False)
    op.create_table('ai_interaction_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['ai_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interaction_feedback_id'), 'ai_interaction_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_ai_interaction_feedback_message_id'), 'ai_interaction_feedback', ['message_id'], unique=False)
    op.create_table('feedback_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_likes_feedback_id'), 'feedback_likes', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_feedback_likes_id'), 'feedback_likes', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_likes_user_id'), 'feedback_likes', ['user_id'], unique=False)
    op.create_table('license_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['license_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_redemptions_id'), 'license_redemptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_license_redemptions_id'), table_name='license_redemptions')
    op.drop_table('license_redemptions')
    op.drop_index(op.f('ix_feedback_likes_user_id'), table_name='feedback_likes')
    op.drop_index(op.f('ix_feedback_likes_id'), table_name='feedback_likes')
    op.drop_index(op.f('ix_feedback_likes_feedback_id'), table_name='feedback_likes')
    op.drop_table('feedback_likes')
    op.drop_index(op.f('ix_ai_interaction_feedback_message_id'), table_name='ai_interaction_feedback')
    op.drop_index(op.f('ix_ai_interaction_feedback_id'), table_name='ai_interaction_feedback')
    op.drop_table('ai_interaction_feedback')
    op.drop_index(op.f('ix_predictions_play_type'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_match_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_prediction_snapshots_match_id'), table_name='prediction_snapshots')
    op.drop_index(op.f('ix_prediction_snapshots_id'), table_name='prediction_snapshots')
    op.drop_table('prediction_snapshots')
    op.drop_index(op.f('ix_odds_history_recorded_at'), table_name='odds_history')
    op.drop_index(op.f('ix_odds_history_match_id'), table_name='odds_history')
    op.drop_index(op.f('ix_odds_history_id'), table_name='odds_history')
    op.drop_table('odds_history')
    op.drop_index(op.f('ix_match_bookmaker_odds_recorded_at'), table_name='match_bookmaker_odds')
    op.drop_index(op.f('ix_match_bookmaker_odds_match_id'), table_name='match_bookmaker_odds')
    op.drop_index(op.f('ix_match_bookmaker_odds_id'), table_name='match_bookmaker_odds')
    op.drop_table('match_bookmaker_odds')
    op.drop_index(op.f('ix_match_ai_reports_match_id'), table_name='match_ai_reports')
    op.drop_table('match_ai_reports')
    op.drop_index(op.f('ix_live_odds_snapshots_recorded_at'), table_name='live_odds_snapshots')
    op.drop_index(op.f('ix_live_odds_snapshots_match_id'), table_name='live_odds_snapshots')
    op.drop_index(op.f('ix_live_odds_snapshots_id'), table_name='live_odds_snapshots')
    op.drop_table('live_odds_snapshots')
    op.drop_index(op.f('ix_license_keys_key'), table_name='license_keys')
    op.drop_index(op.f('ix_license_keys_id'), table_name='license_keys')
    op.drop_table('license_keys')
    op.drop_index(op.f('ix_jingcai_issue_matches_match_id'), table_name='jingcai_issue_matches')
    op.drop_index(op.f('ix_jingcai_issue_matches_issue_id'), table_name='jingcai_issue_matches')
    op.drop_index(op.f('ix_jingcai_issue_matches_id'), table_name='jingcai_issue_matches')
    op.drop_table('jingcai_issue_matches')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_betting_exchange_volumes_match_id'), table_name='betting_exchange_volumes')
    op.drop_table('betting_exchange_volumes')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_messages_session_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_quant_profiles_user_id'), table_name='user_quant_profiles')
    op.drop_index(op.f('ix_user_quant_profiles_id'), table_name='user_quant_profiles')
    op.drop_table('user_quant_profiles')
    op.drop_index(op.f('ix_player_stats_team_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_kickoff_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_group_name'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_id'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_jingcai_issues_issue_id'), table_name='jingcai_issues')
    op.drop_index(op.f('ix_jingcai_issues_id'), table_name='jingcai_issues')
    op.drop_table('jingcai_issues')
    op.drop_index(op.f('ix_fusion_weights_id'), table_name='fusion_weights')
    op.drop_table('fusion_weights')
    op.drop_index(op.f('ix_debounce_entries_scope'), table_name='debounce_entries')
    op.drop_index(op.f('ix_debounce_entries_key'), table_name='debounce_entries')
    op.drop_table('debounce_entries')
    op.drop_index(op.f('ix_accuracy_snapshots_id'), table_name='accuracy_snapshots')
    op.drop_table('accuracy_snapshots')
    # ### end Alembic commands ###
